### ISSUE TITLE
Oh no, ntfy crashed!

### ISSUE THREAD

**Issue by morganism** [binwiederhier/ntfy#1054]
:lady_beetle: **Describe the bug**

Oh no, ntfy crashed 😮

This should obviously not happen. Very sorry about this.
If you have a minute, please report this on GitHub, or let us know via Discord or Matrix.

Stack trace

AbortError: Transaction aborted
  at undefined (AbortError: Transaction aborted:undefined:undefined)
  at timeout (https://ntfy.sh/static/media/index-770c1ce6.js:25852:222)
  at t (https://ntfy.sh/static/media/index-770c1ce6.js:5832:221)
AbortError: Transaction aborted
  at dfe@https://ntfy.sh/static/media/index-770c1ce6.js:409:13961
  at oG@https://ntfy.sh/static/media/index-770c1ce6.js:240:4111
  at mG@https://ntfy.sh/static/media/index-770c1ce6.js:240:7607
  at fde@https://ntfy.sh/static/media/index-770c1ce6.js:372:5839
  at withI18nextTranslation(fde)@https://ntfy.sh/static/media/index-770c1ce6.js:250:3139
  at XL@https://ntfy.sh/static/media/index-770c1ce6.js:61:10331
  at QL@https://ntfy.sh/static/media/index-770c1ce6.js:61:10734
  at j3@https://ntfy.sh/static/media/index-770c1ce6.js:61:29756
  at gG@https://ntfy.sh/static/media/index-770c1ce6.js:240:7018
  at jG@https://ntfy.sh/static/media/index-770c1ce6.js:249:929
  at sfe@https://ntfy.sh/static/media/index-770c1ce6.js:409:12649
  at Suspense

:computer: **Components impacted**

:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

**Comment by GideonBear** [comment]
I got a similar error:
```
AbortError: The transaction was aborted, so the request cannot be fulfilled.
 AbortError: The transaction was aborted, so the request cannot be fulfilled.
  at timeout (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:63434:225)
  at t (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:4051:224)
  at timeout (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:24873:225)
  at t (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:5848:224)

AbortError: The transaction was aborted, so the request cannot be fulfilled.
 AbortError: The transaction was aborted, so the request cannot be fulfilled.
  at at dre (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:413:14805)
  at     at oK (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:243:4080)
  at     at vK (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:243:7740)
  at     at cne (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:376:5897)
  at     at a (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:253:3125)
  at     at Dz (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:64:12750)
  at     at Mz (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:64:12590)
  at     at Rz (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:64:12371)
  at     at zz (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:64:14009)
  at     at B$ (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:64:34058)
  at     at hK (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:243:7124)
  at     at kK (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:252:874)
  at     at sre (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:413:13347)
  at     at Suspense (<anonymous>)
  at     at cre (http://192.168.1.171:1420/static/media/index-B_d1RqKQ.js:413:13592)
```

**Comment by binwiederhier** [comment]
I sadly don't know how to reproduce this. There are more issues like this: #1054, #1250, #787, #876, #1281 -- but they are all 2-3 years old, so I'm hoping this is not relevant anymore. Please feel free to make a new issue or comment here if it's still a problem.
