### ISSUE TITLE
IllegalStateException: Failed to build unique file

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#177]
```
139e314e2665/Images/Primary, contentUri=content://media/external/file/27942, progress=-3)
1647618552728 2022-03-18 15:49:12.728 W NtfyAttachDownload Attachment download failed
Exception:
java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Download/Primary.jpg bucket_display_name=Download volume_name=external_primary date_modified=null date_expires=null _display_name=Primary.jpg mime_type=image/jpeg _data=/storage/emulated/0/Download/Primary.jpg _size=null is_trashed=0 is_pending=0 bucket_id=540528482 relative_path=Download/
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
    at android.os.Parcel.createException(Parcel.java:2409)
    at android.os.Parcel.readException(Parcel.java:2392)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
    at android.content.ContentProviderProxy.update(ContentProviderNative.java:653)
    at android.content.ContentResolver.update(ContentResolver.java:2400)
    at android.content.ContentResolver.update(ContentResolver.java:2362)
    at io.heckel.ntfy.msg.DownloadWorker.downloadAttachment(DownloadWorker.kt:145)
    at io.heckel.ntfy.msg.DownloadWorker.doWork(DownloadWorker.kt:52)
    at androidx.work.Worker$1.run(Worker.java:86)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
```

**Comment by Fallenbagel** [comment]
This happens after I reach a certain limit of attachments of the same name i.e, primary.jpg. Like estimated 30 or 40. After that happens, once every primary.jpg is deleted, the attachments start downloading automatically

**Comment by binwiederhier** [comment]
Not relevant anymore after #181
