### ISSUE TITLE
Error opening https://ntfy.sh/app and switching to "Subscribe to Topic"

### ISSUE THREAD

**Issue by KikyTokamuro** [binwiederhier/ntfy#438]
![image](https://user-images.githubusercontent.com/9868440/195044802-1c315c97-668b-4ae6-bb3e-a6da0b69c1d1.png)

Stacktrace:
```
TypeError: Cannot read properties of undefined (reading 'map')
  at SubscribePage (components/SubscribeDialog.js:50:60)
  at Xh (../node_modules/react-dom/cjs/react-dom.production.min.js:136:167)
  at Wk (../node_modules/react-dom/cjs/react-dom.production.min.js:336:290)
  at uj (../node_modules/react-dom/cjs/react-dom.production.min.js:388:280)
  at uj (../node_modules/react-dom/cjs/react-dom.production.min.js:319:280)
  at uj (../node_modules/react-dom/cjs/react-dom.production.min.js:179:280)
  at Ok (../node_modules/react-dom/cjs/react-dom.production.min.js:87:271)
  at Dk (../node_modules/react-dom/cjs/react-dom.production.min.js:299:273)
  at jg (../node_modules/react-dom/cjs/react-dom.production.min.js:104:127)
  at Ek (../node_modules/react-dom/cjs/react-dom.production.min.js:272:267)

TypeError: Cannot read properties of undefined (reading 'map')
  at at Bf (https://ntfy.sh/static/js/main.04a41eb3.js:2:882676)
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:368512
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at n (https://ntfy.sh/static/js/main.04a41eb3.js:2:360714)
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:437996
  at     at Er (https://ntfy.sh/static/js/main.04a41eb3.js:2:432355)
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:395146
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:434993
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:441375
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:824595
  at     at Df (https://ntfy.sh/static/js/main.04a41eb3.js:2:887083)
  at     at qm (https://ntfy.sh/static/js/main.04a41eb3.js:2:931014)
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:368512
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:755149
  at     at nav
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:343342
  at     at e (https://ntfy.sh/static/js/main.04a41eb3.js:2:930625)
  at     at div
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:10064
  at     at https://ntfy.sh/static/js/main.04a41eb3.js:2:343342
  at     at $b (https://ntfy.sh/static/js/main.04a41eb3.js:2:1071264)
  at     at Pm (https://ntfy.sh/static/js/main.04a41eb3.js:2:915764)
  at     at Am (https://ntfy.sh/static/js/main.04a41eb3.js:2:917870)
  at     at n (https://ntfy.sh/static/js/main.04a41eb3.js:2:971528)
  at     at i (https://ntfy.sh/static/js/main.04a41eb3.js:2:974709)
  at     at Z (https://ntfy.sh/static/js/main.04a41eb3.js:2:344007)
  at     at S (https://ntfy.sh/static/js/main.04a41eb3.js:2:343734)
  at     at C (https://ntfy.sh/static/js/main.04a41eb3.js:2:344119)
  at     at Rm (https://ntfy.sh/static/js/main.04a41eb3.js:2:917130)
  at     at sv (https://ntfy.sh/static/js/main.04a41eb3.js:2:970224)
  at     at Suspense
  at     at Xb

```

**Comment by KikyTokamuro** [comment]
Time passed and the error did not appear again.

**Comment by binwiederhier** [comment]
> Time passed and the error did not appear again.

Well people do say time heals all wounds. Hehe.

No but anyway, this should not happen. I'll check it out later. Thank you for reporting.
