### ISSUE TITLE
NTFY Crashed

### ISSUE THREAD

**Issue by oussamaelhajoui** [binwiederhier/ntfy#539]
ntfy local server hosted crashed

```
sparky@sparky:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

command used to serve
```
sudo ntfy serve --listen-http :80 --base-url http://local.syncfast.nl --upstream-base-url https://ntfy.sh --auth-file /var/lib/ntfy/user.db
```

Stack trace
DatabaseClosedError: UnknownError Internal error.
 UnknownError: Internal error.
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:16621:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:17696:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:25902:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:26933:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:19137:1)
  at all (app/UserManager.js:15:5)
  at tryCatch (../node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:16:44)
  at maybeInvokeDelegate (../node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:21:125)
DatabaseClosedError: UnknownError Internal error.
 UnknownError: Internal error.
  at at r_ (http://77.164.145.64/static/js/main.d80020db.js:2:1077062)
  at     at Rm (http://77.164.145.64/static/js/main.d80020db.js:2:920645)
  at     at Dm (http://77.164.145.64/static/js/main.d80020db.js:2:922811)
  at     at n (http://77.164.145.64/static/js/main.d80020db.js:2:976906)
  at     at i (http://77.164.145.64/static/js/main.d80020db.js:2:980087)
  at     at C (http://77.164.145.64/static/js/main.d80020db.js:2:344292)
  at     at S (http://77.164.145.64/static/js/main.d80020db.js:2:344014)
  at     at O (http://77.164.145.64/static/js/main.d80020db.js:2:344403)
  at     at Bm (http://77.164.145.64/static/js/main.d80020db.js:2:922071)
  at     at fv (http://77.164.145.64/static/js/main.d80020db.js:2:975360)
  at     at Suspense
  at     at c_

**Comment by binwiederhier** [comment]
This is an error in Dexie.js, the library that I used to talked to IndexedDB in the browser. To the best of my knowledge, there is nothing you can do about this but wipe the local browser database. I checked the Dexie.js issues (https://github.com/dexie/Dexie.js/issues), but couldn't find anything about this.

# Workaround
To wipe the local browser DB, press F12 to open the developer console and delete the IndexedDB database. **This will sadly lose all your subscriptions and settings**:

## Firefox
F12 -> Storage -> Indexed DB

![image](https://user-images.githubusercontent.com/664597/206858805-91ff2649-346b-46d8-893b-1a3bf21fd5c1.png)

## Chrome 
F12 -> Application -> Indexed DB
![image](https://user-images.githubusercontent.com/664597/206858859-732a8637-f5e7-4eda-8e2d-f01b566d2de9.png)
