### ISSUE TITLE
firefox 108.0.2 crash webapp

### ISSUE THREAD

**Issue by 143981** [binwiederhier/ntfy#574]
DatabaseClosedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.
 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
  at undefined (DatabaseClosedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.:undefined:undefined)
  at undefined ( UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.:undefined:undefined)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:16621:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:16809:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:15448:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:10180:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:10937:1)
  at from (../node_modules/dexie/dist/modern/dexie.min.mjs:11298:1)

DatabaseClosedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.
 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
  at s_@https://ntfy.sh/static/js/main.226af0b6.js:2:1080827
  at Dm@https://ntfy.sh/static/js/main.226af0b6.js:2:924178
  at Vm@https://ntfy.sh/static/js/main.226af0b6.js:2:926532
  at n@https://ntfy.sh/static/js/main.226af0b6.js:2:980772
  at i@https://ntfy.sh/static/js/main.226af0b6.js:2:983951
  at C@https://ntfy.sh/static/js/main.226af0b6.js:2:346370
  at S@https://ntfy.sh/static/js/main.226af0b6.js:2:346090
  at O@https://ntfy.sh/static/js/main.226af0b6.js:2:346479
  at Km@https://ntfy.sh/static/js/main.226af0b6.js:2:925792
  at wv@https://ntfy.sh/static/js/main.226af0b6.js:2:979224
  at Suspense
  at d_

**Comment by 143981** [comment]
Sorry, problem with my profile firefox.
