### ISSUE TITLE
TypeError: Li.disallowed_topics is undefined

### ISSUE THREAD

**Issue by julianlam** [binwiederhier/ntfy#632]
Hi @binwiederhier! ntfy crashed 😮

Here's the stack trace it told me to report :blush: 

```
TypeError: Li.disallowed_topics is undefined
  at disallowedTopic (app/utils.js:4:47)
  at disallowedTopic (app/utils.js:8:40)
  at validTopic (components/PublishDialog.js:43:88)
  at Qj (../node_modules/react-dom/cjs/react-dom.production.min.js:331:244)
  at Yk (../node_modules/react-dom/cjs/react-dom.production.min.js:113:286)
  at Dk (../node_modules/react-dom/cjs/react-dom.production.min.js:184:273)
  at jg (../node_modules/react-dom/cjs/react-dom.production.min.js:104:127)
  at Xk (../node_modules/react-dom/cjs/react-dom.production.min.js:469:283)
  at Tk (../node_modules/react-dom/cjs/react-dom.production.min.js:400:281)
  at d)break;b=a.eventTimes;for (../node_modules/react-dom/cjs/react-dom.production.min.js:271:270)
  at J (../node_modules/scheduler/cjs/scheduler.production.min.js:204:13)
  at S (../node_modules/scheduler/cjs/scheduler.production.min.js:127:14)

TypeError: Li.disallowed_topics is undefined
  at t@https://ntfy.sh/static/js/main.7a56b157.js:2:1144182
  at px@https://ntfy.sh/static/js/main.7a56b157.js:2:1161970
  at div
  at 9886/a/<@https://ntfy.sh/static/js/main.7a56b157.js:2:10090
  at p<@https://ntfy.sh/static/js/main.7a56b157.js:2:378580
  at oj@https://ntfy.sh/static/js/main.7a56b157.js:2:1212109
  at Wl@https://ntfy.sh/static/js/main.7a56b157.js:2:792458
  at Jl@https://ntfy.sh/static/js/main.7a56b157.js:2:794879
  at n@https://ntfy.sh/static/js/main.7a56b157.js:2:1137437
  at i@https://ntfy.sh/static/js/main.7a56b157.js:2:1140616
  at O@https://ntfy.sh/static/js/main.7a56b157.js:2:379250
  at P@https://ntfy.sh/static/js/main.7a56b157.js:2:378970
  at E@https://ntfy.sh/static/js/main.7a56b157.js:2:379359
  at $l@https://ntfy.sh/static/js/main.7a56b157.js:2:794139
  at ob@https://ntfy.sh/static/js/main.7a56b157.js:2:1085499
  at Suspense
  at cj@https://ntfy.sh/static/js/main.7a56b157.js:2:1216006
```

**Comment by julianlam** [comment]
I am not certain when it crashed, when I opened my laptop from standby, that was in the tab. I don't think that is relevant, but maybe it is.

**Comment by binwiederhier** [comment]
Hard refresh the app on the browser.

**Comment by julianlam** [comment]
Yep, that takes care of a great many issues :laughing: 

It's probably a one-off, but re-open if it actually is important :eyes:

**Comment by binwiederhier** [comment]
I'm very confused as to why the browser is caching the old stuff. I do control the cache headers, hm...
