### ISSUE TITLE
PWA on iOS sometimes crashes with an IndexedDB error

### ISSUE THREAD

**Issue by nimbleghost** [binwiederhier/ntfy#787]
:lady_beetle: **Describe the bug**

When resuming the installed PWA from the background, it sometimes crashes with an error from IndexedDB/Dexie:

`UnknownError: Attempt to get count from database without an in-progress transaction`

:computer: **Components impacted**

Web app, iOS only

:bulb: **Screenshots and/or logs**

```
UnknownError: Attempt to get count from database without an in-progress transaction
 UnknownError: Attempt to get count from database without an in-progress transaction
  at undefined (UnknownError: Attempt to get count from database without an in-progress transaction:undefined:undefined)
  at undefined ( UnknownError: Attempt to get count from database without an in-progress transaction:undefined:undefined)
  at timeout (https://staging.ntfy.sh/static/media/index-06629207.js:62485:222)
  at t (https://staging.ntfy.sh/static/media/index-06629207.js:4036:221)
  at zh ([native code]:undefined:undefined)
  at timeout (https://staging.ntfy.sh/static/media/index-06629207.js:24470:222)
  at t (https://staging.ntfy.sh/static/media/index-06629207.js:5832:221)
 
UnknownError: Attempt to get count from database without an in-progress transaction
 UnknownError: Attempt to get count from database without an in-progress transaction
  at Rq@https://staging.ntfy.sh/static/media/index-06629207.js:336:71367
  at x8@https://staging.ntfy.sh/static/media/index-06629207.js:240:3960
  at O8@https://staging.ntfy.sh/static/media/index-06629207.js:240:6876
  at QH@https://staging.ntfy.sh/static/media/index-06629207.js:317:5812
  at withI18nextTranslation(QH)@https://staging.ntfy.sh/static/media/index-06629207.js:268:3139
  at i$@https://staging.ntfy.sh/static/media/index-06629207.js:61:18625
  at s$@https://staging.ntfy.sh/static/media/index-06629207.js:61:19028
  at Q$@https://staging.ntfy.sh/static/media/index-06629207.js:61:29591
  at A8@https://staging.ntfy.sh/static/media/index-06629207.js:240:6337
  at M8@https://staging.ntfy.sh/static/media/index-06629207.js:249:781
  at Suspense
  at Aq@https://staging.ntfy.sh/static/media/index-06629207.js:336:70571
```

:crystal_ball: **Additional context**

 
WebKit Bug: <https://bugs.webkit.org/show_bug.cgi?id=197050>

Other projects that ran into the same or similar issue

- <https://github.com/firebase/firebase-js-sdk/issues/2232>
- <https://github.com/pouchdb/pouchdb/issues/8329>

**Comment by multicolorist** [comment]
Yes, this happens almost every day so would be nice for it to be fixed.

**Comment by binwiederhier** [comment]
I sadly don't know how to reproduce this. There are more issues like this: #1054, #1250, #787, #876, #1281 -- but they are all 2-3 years old, so I'm hoping this is not relevant anymore. Please feel free to make a new issue or comment here if it's still a problem.
