### ISSUE TITLE
web ntsf crashed

### ISSUE THREAD

**Issue by fromozuzu** [binwiederhier/ntfy#844]
RangeError: Incorrect locale information provided
  at log (https://ntfy.sh/static/media/index-9e24212a.js:320:286)
  at lse (https://ntfy.sh/static/media/index-9e24212a.js:281:326)
  at isMounted (https://ntfy.sh/static/media/index-9e24212a.js:19518:38)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:44027:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39763:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39691:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39545:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:35913:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:34864:40)

RangeError: Incorrect locale information provided
  at at use (https://ntfy.sh/static/media/index-9e24212a.js:326:238)
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:22350
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:20669
  at     at div
  at     at div
  at     at t (https://ntfy.sh/static/media/index-9e24212a.js:263:1464)
  at     at IR (https://ntfy.sh/static/media/index-9e24212a.js:286:86948)
  at     at ise (https://ntfy.sh/static/media/index-9e24212a.js:286:86525)
  at     at rse (https://ntfy.sh/static/media/index-9e24212a.js:286:86333)
  at     at oK (https://ntfy.sh/static/media/index-9e24212a.js:240:3933)
  at     at pK (https://ntfy.sh/static/media/index-9e24212a.js:240:6226)
  at     at main
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:13098
  at     at Rde (https://ntfy.sh/static/media/index-9e24212a.js:409:15094)
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:13098
  at     at Ode (https://ntfy.sh/static/media/index-9e24212a.js:409:13968)
  at     at oK (https://ntfy.sh/static/media/index-9e24212a.js:240:3933)
  at     at gK (https://ntfy.sh/static/media/index-9e24212a.js:240:6851)
  at     at Cce (https://ntfy.sh/static/media/index-9e24212a.js:372:5834)
  at     at i (https://ntfy.sh/static/media/index-9e24212a.js:250:3140)
  at     at GN (https://ntfy.sh/static/media/index-9e24212a.js:61:18729)
  at     at YN (https://ntfy.sh/static/media/index-9e24212a.js:61:19114)
  at     at D3 (https://ntfy.sh/static/media/index-9e24212a.js:61:29727)
  at     at fK (https://ntfy.sh/static/media/index-9e24212a.js:240:6285)
  at     at _K (https://ntfy.sh/static/media/index-9e24212a.js:249:744)
  at     at Pde (https://ntfy.sh/static/media/index-9e24212a.js:409:12627)
  at     at Suspense
  at     at Ade (https://ntfy.sh/static/media/index-9e24212a.js:409:12872)

**Comment by Potat0000** [comment]
Duplicated #841
