### ISSUE TITLE
Recognize imported ca certs in android

### ISSUE THREAD

**Issue by keith24** [binwiederhier/ntfy#87]
Feature request for the android app.  I'm self hosting my ntfy instance and want to use my self-signed cert.  The custom CA cert is imported in my Android OS... some apps recognize it and some don't.  I request that ntfy trusts these user-imported CAs.  I imagine they are easily accessible from the android SDK and/or your HTTP request library.

**Comment by keith24** [comment]
The errors I get with my server are like this: 

```
java.security.cert.CertPathValidatorExecption: Trust anchor for certificate path not found.  
```

**Comment by binwiederhier** [comment]
Tested with a self-signed CA and certs in the emulator: https://github.com/binwiederhier/ntfy-android/commit/54dd90d415dda9f066cb4680bab79bfed24e9433

It was quite difficult to generate all of those, but it works. The one thing to note is that it didn't work with an internal IP address. It had to be a hostname. I used 10.0.2.2.nip.io which resolves to 10.0.2.2 for testing, but in your setup, you probably should have a real DNS server.

I'm closing this. It'll be in the next release, which will be a week or so I think. Until then you can probably use HTTP :-D

Thank you for resporting this and that's for pointing me in the right direction!!

**Comment by keith24** [comment]
You mean... you couldn't get the cert to work with an ip, even if you set it in the server certificate's Subject Alternative Names?  Something like: 

```
...
[SAN]
subjectAltName=DNS:mydomain.tld,IP:10.0.2.2
```

In the CSR should allow a self-signed cert to work for both `https://mydomain.tld` and `https://10.0.2.2`.  I have domain-/hostnames so it doesn't affect me, but I feel like it _should_ work.  

If the android sdk doesn't support it, however, what can you do?  🤷

**Comment by binwiederhier** [comment]
Ohhhh there is an IP: field. Yeah i didn't do that. I mean it should work. If you want I can build you an APK and you can try it.

**Comment by keith24** [comment]
Nah.  If `DNS:` works, `IP:` should also work.  Or else it's android's fault anyway.

**Comment by keith24** [comment]
Working in v1.6.0

**Comment by tctlrd** [comment]
I have caddy serving up a letsencrypt wildcard certificate for ntfy with everything working except that I am receiving this error if I attempt to use https.
`java.security.cert.CertPathValidatorExecption: Trust anchor for certificate path not found.`
Any ideas?

```
This is a log of the ntfy Android app. The log shows up to 1,000 entries.

Device info:
--
ntfy: 1.16.0 (fdroid)
OS: 4.4.302-dos.p209+
Android: 13 (SDK 33)
Model: xx
Product: xx

--
Settings:                    
{
  "autoDeleteSeconds": 2592000,
  "autoDownloadMaxSize": 1048576,
  "broadcastEnabled": true,
  "connectionProtocol": "ws",
  "darkMode": -1,
  "defaultBaseUrl": "https://nf.fqdn.xx",
  "lastSharedTopics": [],
  "minPriority": 1,
  "mutedUntil": 0,
  "recordLogs": true
}

Logs
--
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.heckel.ntfy.msg.ApiService.checkAuth(ApiService.kt:156)
	at io.heckel.ntfy.ui.AddFragment$checkReadAndMaybeShowLogin$1.invokeSuspend(AddFragment.kt:209)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.```
