### ISSUE TITLE
Change Languegue, error

### ISSUE THREAD

**Issue by thomazcia** [binwiederhier/ntfy#912]
:lady_beetle: **Describe the bug**
I change de languague to Portugues Brasil then click in Account, show error.

:computer: **Components impacted**
ntfy.sh

:bulb: **Screenshots and/or logs**
RangeError: Incorrect locale information provided
  at log (https://ntfy.sh/static/media/index-9e24212a.js:320:286)
  at w (https://ntfy.sh/static/media/index-9e24212a.js:41237:391)
  at w (https://ntfy.sh/static/media/index-9e24212a.js:40450:391)
  at isMounted (https://ntfy.sh/static/media/index-9e24212a.js:19518:38)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:44027:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39763:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39691:40)
  at callback (https://ntfy.sh/static/media/index-9e24212a.js:39545:40)

RangeError: Incorrect locale information provided
  at at Eue (https://ntfy.sh/static/media/index-9e24212a.js:391:39667)
  at     at div
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:135:63751
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:41169
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:135:61152
  at     at Pue (https://ntfy.sh/static/media/index-9e24212a.js:391:38890)
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:22350
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:20669
  at     at yue
  at     at oK (https://ntfy.sh/static/media/index-9e24212a.js:240:3933)
  at     at pK (https://ntfy.sh/static/media/index-9e24212a.js:240:6226)
  at     at main
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:13098
  at     at Rde (https://ntfy.sh/static/media/index-9e24212a.js:409:15094)
  at     at div
  at     at https://ntfy.sh/static/media/index-9e24212a.js:55:6185
  at     at https://ntfy.sh/static/media/index-9e24212a.js:61:13098
  at     at Ode (https://ntfy.sh/static/media/index-9e24212a.js:409:13968)
  at     at oK (https://ntfy.sh/static/media/index-9e24212a.js:240:3933)
  at     at gK (https://ntfy.sh/static/media/index-9e24212a.js:240:6851)
  at     at Cce (https://ntfy.sh/static/media/index-9e24212a.js:372:5834)
  at     at i (https://ntfy.sh/static/media/index-9e24212a.js:250:3140)
  at     at GN (https://ntfy.sh/static/media/index-9e24212a.js:61:18729)
  at     at YN (https://ntfy.sh/static/media/index-9e24212a.js:61:19114)
  at     at D3 (https://ntfy.sh/static/media/index-9e24212a.js:61:29727)
  at     at fK (https://ntfy.sh/static/media/index-9e24212a.js:240:6285)
  at     at _K (https://ntfy.sh/static/media/index-9e24212a.js:249:744)
  at     at Pde (https://ntfy.sh/static/media/index-9e24212a.js:409:12627)
  at     at Suspense
  at     at Ade (https://ntfy.sh/static/media/index-9e24212a.js:409:12872)

:crystal_ball: **Additional context**
I back to English and ok

**Comment by binwiederhier** [comment]
I believe this should be fixed by #922; will be shipped with the next release.
